spring.application.name=springscurityex


spring.security.user.name=ali
spring.security.user.password=123


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=security;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect